const FeedActionTypes = {
  ADD_LIKE: "ADD_LIKE",
  ADD_COMMENT: "ADD_COMMENT",
  FETCH_POST_START: "FETCH_POST_START",
  FETCH_POST_SUCCESS:"FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE:"FETCH_POST_FAILURE",
  POST_PICTURE_START: "POST_PICTURE_START",
  POST_PICTURE_SUCCESS: "POST_PICTURE_SUCCESS",
  POST_PICTURE_FAILURE: "POST_PICTURE_FAILURE"
};
export default FeedActionTypes;