export const PROFILE_START = 'PROFILE_START';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';


export const EDIT_PROFILE_START = 'EDIT_PROFILE_START'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE'


export const CREATE_POST_START = 'CREATE_POST_START'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'


export const CHECK_STATUS_FRIEND = 'CHECK_STATUS_FRIEND'

export const CLEAR_PROFILE_STATE = 'CLEAR_PROFILE_STATE'